[tool.pytest.ini_options]
pythonpath = [
    "."
]
asyncio_mode = "auto"
testpaths = [
    "tests"
]
python_files = ["test_*.py"]
python_classes = ["Test*"]
python_functions = ["test_*"]
markers = [
    "asyncio: mark test as async",
] 