[tool.pytest.ini_options]
pythonpath = [
    "."
]
asyncio_mode = "auto"
testpaths = [
    "tests"
]
python_files = ["test_*.py"]
python_classes = ["Test*"]
python_functions = ["test_*"]
asyncio_default_fixture_loop_scope = "function"
markers = [
    "asyncio: mark test as async",
    "integration: marks tests as integration tests",
] 